# This is a basic workflow to help you get started with Actions

name: get-started
run-name: Triggered by ${{github.event_name}} event

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["features/**", "main"]
    # you can also include regex filters
  # pull_request:
  #   branches: [ "main" ]
  #   paths: '**/*.js'
  #   paths-ignore:
  #     - '**/README.md'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "job01"
  job01:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v3
        # with:
        #   ref: any inputs to pass

      - name: Greetings
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: some-artifact
          path: |
            # ${{github.workspace}}/README.md
            artifacts101/README.md

  job02:
    needs: job01 # dependency
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        run: |
          echo This is the second job.

      - name: workflow metadata
        run: |
          echo "${{toJSON(github)}}" # all metadata. It also has functions like toJSON and fromJSON
          echo "workflow: ${{github.workflow}}, action: ${{github.action}}, run-id: ${{github.run_id}}, run-number: ${{github.run_number}}"

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: some-artifact
          path: |
            artifacts101

      - name: List downloaded files
        run: ls -R
        working-directory: /download/artifacts

  basicOutputs:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Output a value
        id: abc10
        run: echo "op01=yesthisisoutputhere" >> $GITHUB_OUTPUT

      - name: Use the output
        run: echo "The output is ${{ steps.abc10.outputs.op01 }}"

  OutputbtwJobs:
    runs-on: ubuntu-latest
    outputs:
      op02: ${{ steps.toanotherjob.outputs.op01 }}

    steps:
      - name: Output a value
        id: toanotherjob
        run: echo "op01=yesitsoutputbetweenjobs" >> $GITHUB_OUTPUT

  GetOutputFromAnotherJob:
    runs-on: ubuntu-latest
    needs: OutputbtwJobs
    steps:
      - name: Use the output
        run: echo "The output is ${{ needs.OutputbtwJobs.outputs.op02 }}"

  GetOutputFromAnotherJobv2:
    runs-on: ubuntu-latest
    needs: OutputbtwJobs
    steps:
      - env:
          OUTPUT1: ${{ needs.OutputbtwJobs.outputs.op02 }}
        run: echo "The output is $OUTPUT1"
